name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '17'
      - uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '8'
          targets: 'JAVA_8_HOME'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build --info
